services:
  proxy-server-postgres:
    container_name: proxy-server-postgres
    image: postgis/postgis:16-3.4
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - proxy-server-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      POSTGIS_ENABLE_OUTDB_RASTERS: 1
      POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
    env_file: .env
    networks:
      - proxy-server-network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: proxy-server-postgres

volumes:
  proxy-server-postgres-data:
    name: proxy-server-postgres-data
    driver: local

networks:
  proxy-server-network:
    name: proxy-server-network
    driver: bridge
    attachable: true
