services:
  # proxy-server-mongo:
  #   container_name: proxy-server-mongo
  #   image: mongo:8.0.10-noble
  #   restart: always
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}
  #   volumes:
  #     - proxy-server-mongo-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #   env_file: .env
  #   networks:
  #     - proxy-server-network
  #   command:
  #     - "--storageEngine"
  #     - wiredTiger
  #     - "--auth"
  #   hostname: proxy-server-mongo

  # proxy-server-kafka-broker:
  #   container_name: proxy-server-kafka-broker
  #   image: apache/kafka:latest
  #   ports:
  #     - ${KAFKA_PORT}:${KAFKA_PORT}
  #     - ${KAFKA_CONTROLLER_PORT}:${KAFKA_CONTROLLER_PORT}
  #   environment:
  #     KAFKA_NODE_ID: ${KAFKA_NODE_ID}
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://proxy-server-kafka-broker:${KAFKA_PORT}
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@proxy-server-kafka-broker:${KAFKA_CONTROLLER_PORT}
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
  #     KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
  #   env_file: .env
  #   networks:
  #     - proxy-server-network
  #   hostname: proxy-server-kafka-broker

  # proxy-server-kafka-ui:
  #   container_name: proxy-server-kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   depends_on:
  #     - proxy-server-kafka-broker
  #   ports:
  #     - ${KAFKA_UI_PORT}:${KAFKA_UI_PORT}
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: proxy-server-kafka-broker:${KAFKA_PORT}
  #   env_file: .env
  #   networks:
  #     - proxy-server-network
  #   hostname: proxy-server-kafka-ui

  proxy-server-redis:
    container_name: proxy-server-redis
    image: redis:8.0.2-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - proxy-server-redis-data:/data
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: ${REDIS_DATABASES}
    env_file: .env
    networks:
      - proxy-server-network
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: proxy-server-redis

  proxy-server-redis-insight:
    container_name: proxy-server-redis-insight
    image: redislabs/redisinsight:latest
    restart: always
    depends_on:
      proxy-server-redis:
        condition: service_healthy
    ports:
      - ${RI_PORT}:${RI_PORT}
    volumes:
      - proxy-server-redis-insight-data:/usr/src/app/redisinsight/api/data
    environment:
      REDISINSIGHT_DISABLE_ENCRYPTION: ${RI_DISABLE_ENCRYPTION}
    env_file: .env
    networks:
      - proxy-server-network
    command: |
      sh -c " mkdir -p /usr/src/app/redisinsight/api/data && chown -R node:node /usr/src/app/redisinsight/api/data && ./docker-entry.sh "
    hostname: proxy-server-redis-insight
    user: '0:0'

  proxy-server-postgres:
    container_name: proxy-server-postgres
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - proxy-server-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    env_file: .env
    networks:
      - proxy-server-network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: proxy-server-postgres

volumes:
  # proxy-server-mongo-data:
  #   name: proxy-server-mongo-data
  #   driver: local
  proxy-server-redis-data:
    name: proxy-server-redis-data
    driver: local
  proxy-server-redis-insight-data:
    name: proxy-server-redis-insight-data
    driver: local
  proxy-server-postgres-data:
    name: proxy-server-postgres-data
    driver: local

networks:
  proxy-server-network:
    name: proxy-server-network
    driver: bridge
    attachable: true
